[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
crosspay = "4fy5wximsVYsVYwLp5VrgjqfUq8NyEXG1nisKuwkS8Vq"

[programs.devnet]
crosspay = "4fy5wximsVYsVYwLp5VrgjqfUq8NyEXG1nisKuwkS8Vq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet" # switch as required e.g., devnet
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
